// get list user events
export const GET_STORE_INFOMATION_START = 'GET_STORE_INFOMATION_START';
export const GET_STORE_INFOMATION_SUCCESS = 'GET_STORE_INFOMATION_SUCCESS';
export const GET_STORE_INFOMATION_FALURE = 'GET_STORE_INFOMATION_FALURE';

export const UPLOAD_IMAGE_START = 'UPLOAD_IMAGE_START';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
